<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en-us"><head>

  <link rel="icon"  type="image/png" href="/myemsl/brand/favicon.ico">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <style type="text/css" media="all">  @import "/myemsl/brand/myemsl.css"; </style>
  <style type="text/css" media="all">

#level1Nav, #main, #footer, #mainTitle {
  margin: auto;
  width: 950px;
  position: relative;
}

#level1Nav {
  list-style: none;
  text-align: center;
  background-color: #00aa00;
  margin: 0.75em auto;
}

#level1Nav li {
  display: inline;
}

#level1Nav a {
  text-transform: uppercase;
  color: white;
  font-weight: bold;
  text-decoration: none;
  line-height: 36px;
  padding: 11px 18px;
  white-space: nowrap;
//  border-right: 1px solid #e99519;
//  border-left: 1px solid #e99519;
}

#level1Nav a:hover {
  text-decoration: underline;
  color: white;
  background-color: #007700;
}

  </style>

  <script type="text/javascript" src="/myemsl/api/1/jquery.min.js"></script>

